#include<bits/stdc++.h>
using namespace std;
#define rep(i,a,n) for(int i=(a);i<(int)(n);i++)
#define all(x) (x).begin(),(x).end()
#define sz(x) ((int)(x).size())
#define MP make_pair
#define PB push_back
#define AA first
#define BB second
#define OP begin()
#define ED end()
#define SZ size()
typedef long long LL;
typedef pair<int,int> PII;
typedef pair<LL,LL> PLL;
typedef vector<int> VI;
typedef vector<LL> VL;
#define cmin(x,y) x=min(x,y)
#define cmax(x,y) x=max(x,y)
const LL MOD = 1000000007;
const double PI = acos(-1.);
const double eps = 1e-9;
LL modPow(LL a,LL b,LL MOD){
	LL ret=1;for(;b;b>>=1){
		if(b&1)ret=ret*a%MOD;a=a*a%MOD;
	}return ret;
}
int g[1<<20|1];
int h[1005][1005];
int f[1<<20|1];
class DistinguishableSetDiv1 {
public:
	int count( vector <string> answer ) {
		int n=sz(answer);
		int m=sz(answer[0]);
		memset(g,0,sizeof g);
		memset(f,0,sizeof f);
		rep(i,0,n)rep(j,i+1,n){
			h[i][j]=0;
			rep(k,0,m)if(answer[i][k]!=answer[j][k])
				h[i][j]|=1<<k;
			g[h[i][j]]=1;
		}
		if(g[0])return 0;
		rep(i,0,1<<m)if(g[i]){
			rep(j,0,m){
				if(i>>j&1);
				else g[i|(1<<j)]=1;
			}
		}
		vector<int>L;
		for(int i=(1<<m)-1;i>=0;i--)if(g[i]){
			rep(j,0,m)if(i>>j&1){
				if(g[i^(1<<j)]){
					g[i]=0;
					break;
				}
			}
			if(g[i])L.PB(i);
		}
		int ret=0;
		f[(1<<m)-1]=1;
		ret++;
		for(int i=(1<<m)-2;i>=0;i--){
			int may=1;
			rep(j,0,m){
				if(i>>j&1);
				else may&=f[i|(1<<j)];
			}
			if(may){
				f[i]=1;
				for(auto x:L){
					if(x&i);
					else {
						f[i]=0;
						break;
					}
				}
			}
			ret+=f[i];
		}
		return ret;
	}
};

// BEGIN CUT HERE
namespace moj_harness {
	int run_test_case(int);
	void run_test(int casenum = -1, bool quiet = false) {
		if ( casenum != -1 ) {
			if ( run_test_case( casenum ) == -1 && !quiet )
				cerr << "Illegal input! Test case " << casenum << " does not exist." << endl;
			return;
		}
		
		int correct = 0, total = 0;
		for ( int i=0;; ++i ) {
			int x = run_test_case(i);
			if ( x == -1 ) {
				if ( i >= 100 ) break;
				continue;
			}
			correct += x;
			++total;
		}
		
		if ( total == 0 ) {
			cerr << "No test cases run." << endl;
		} else if ( correct < total ) {
			cerr << "Some cases FAILED (passed " << correct << " of " << total << ")." << endl;
		} else {
			cerr << "All " << total << " tests passed!" << endl;
		}
	}
	
	int verify_case(int casenum, const int &expected, const int &received, clock_t elapsed) { 
		cerr << "Example " << casenum << "... "; 
		
		string verdict;
		vector<string> info;
		char buf[100];
		
		if (elapsed > CLOCKS_PER_SEC / 200) {
			sprintf(buf, "time %.2fs", elapsed * (1.0/CLOCKS_PER_SEC));
			info.push_back(buf);
		}
		
		if ( expected == received ) {
			verdict = "PASSED";
		} else {
			verdict = "FAILED";
		}
		
		cerr << verdict;
		if (!info.empty()) {
			cerr << " (";
			for (int i=0; i<(int)info.size(); ++i) {
				if (i > 0) cerr << ", ";
				cerr << info[i];
			}
			cerr << ")";
		}
		cerr << endl;
		
		if (verdict == "FAILED") {
			cerr << "    Expected: " << expected << endl; 
			cerr << "    Received: " << received << endl; 
		}
		
		return verdict == "PASSED";
	}

	int run_test_case( int casenum ) {
		switch( casenum ) {
		case 0: {
			string answer[]           = {"AA","AB","CC"};
			int expected__            = 2;

			clock_t start__           = clock();
			int received__            = DistinguishableSetDiv1().count( vector <string>( answer, answer + ( sizeof answer / sizeof answer[0] ) ) );
			return verify_case( casenum, expected__, received__, clock()-start__ );
		}
		case 1: {
			string answer[]           = {"XYZ","XYZ","XYZ"};
			int expected__            = 0;

			clock_t start__           = clock();
			int received__            = DistinguishableSetDiv1().count( vector <string>( answer, answer + ( sizeof answer / sizeof answer[0] ) ) );
			return verify_case( casenum, expected__, received__, clock()-start__ );
		}
		case 2: {
			string answer[]           = {"AAAA","BACA","CDCE"};
			int expected__            = 11;

			clock_t start__           = clock();
			int received__            = DistinguishableSetDiv1().count( vector <string>( answer, answer + ( sizeof answer / sizeof answer[0] ) ) );
			return verify_case( casenum, expected__, received__, clock()-start__ );
		}
		case 3: {
			string answer[]           = {"XYZ","XAB","YAC"};
			int expected__            = 5;

			clock_t start__           = clock();
			int received__            = DistinguishableSetDiv1().count( vector <string>( answer, answer + ( sizeof answer / sizeof answer[0] ) ) );
			return verify_case( casenum, expected__, received__, clock()-start__ );
		}
		case 4: {
			string answer[]           = {"XRFQUHISFHHZRRLFHXJD","JKSPAZTUDULANQSJZCCE","LLGCCTJJSSNDFHTHGOBJ","IMLYEDHEHLKTXQXZLHLD","BAHIHAPPQQBYEMYJSGNZ","RZUQQUQDBDHEDQNMSEDI","XEIBRHMLPBMIBHZRBRWE","UDKZTZNNEQVDVEEONTZC","ULMVULOXELDAOOBKPOXT","FVYCBDSOWRSQEGOZUCYY","NCZEQAQFRPBYMZANESDC","LVVPCJQWLPWBRXHJYZQR","ORPDTRQZLUCYRXPTGGRT","XOWQLDBLCRETLTYGMOFX","KHVCELXMTPGSFCISILEM","CIHPEFVQUBQEINIPYGBT","VHLCMVUUGAILLQARVWHR","XZWHNEWNMYHHHSLTQIPW","IYHVOIMLEWDDVBKKHHYU","HFBOZPKPXBOHZVDPFRDL","NGOLHBVOKVIRAMHCDRRA","TFHUDKKICPWRVKEENCSX","XDQYRYCUPTUKBDFEQROU","GKLBXSHKUBKREARXYTRO","PNYQTFUJWKDCVQFSKMEE","OOWUPPSNJLDYBEQUJMDG","WIIRAQLLEQPSENPTDHJO","UMMVQERAQWIMESGHIRSN","HJHOXWJCFSQCHEXZIRBY","NJMSESZMMTBTCJJBHTDN","NVRWZQYJHZJVLWPPQQDC","JFYNQHPXCUMSSDORWMDD","OMYZKPOBFTDQYBEQLVQN","RCFJIWDEIGJWUKXFZNGF","HLXHPBYAYOPSSXBCTGID","MSCJEZODPWKWJIFYLDAM","TQEOPHSIOBNCVPNZRBEG","ZRCJZJJMNMAIEEWTOPDE","SQIPGWQZZUFBLJMMSVBH","HBQLGOGWFJAZAKOIGEHI","BOJOXVBRQCZADRNLHUJP","DLOFWFNCLWMOKVDJQGBJ","IALNTYBASKPYWGDSLTWY","PJNAGQLXWMIGOTVHRWKM","HBMFHPZUIVVAGICNANMY","AUEQNZYGYKUFLGMVYLRI","GMIPWMCWAOUAIYQXAQFY","CAFQIRLGEERMTBBPOFMO","TIQDJICJBIJDIQTSHGBL","NSXGVBVJGJZCSPFDAKMB","SXGCNCUWIXJXRIDNJBWQ","KYSENZHPJVQDSZFHBCDL","ZMJRVMEGNCYAASEQSMFD","JYHCZOJAQPLQBWJYJPFY","RDYUYFMQTRVCREGQTSSJ","HEBKAMLLBQMTVKPVRBLK","UJPMNVEGNXSUDTHFGSTJ","KFEHRTDJUQVRZKFNGJTT","ILQLHXTPRMYBRDIIYNTT","EPKDZPSFAMBJZRWIQPZH","DYKUDUFBIYWMNIRNZKSA","YVLXMJIEZHNCHXZKUEOC","EKQSTHFSRZUPXFPLRZQQ","GFUOFVAZBOBGBRYUYFOS","GJHDQYPHXHZGMWWRRWQT","NTBOMZINGYFOHOSAPJJM","QJSEHOYYNQTAKUOWVYLD","YQSGHMIWXRIPCDTJTRKG","KFGUCWSZWEDVWXDDLNBI","GKXJPSUIMGPWOXSSWKRU","QWRNVWSGJUOQGNBXGXFU","EWQUWIMSUDOLCGAXCUEO","QUEWIHTQEBKKXAEVKSNG","WERAMTXOQDCGYIFIPAAU","DKGBMLWYDMEBSYDERBSJ","GXQEHXOXZOTDAZEMMCKS","QRVIPZOICJSIGKPNHDMI","UFLUHRJTUVNMMJXBILKM","UEUCOJSXPEFJMRFVIOQE","METYPSCZDOLASFEGPWFE","DMPRDUOOLEUXINXXHZWN","NHNFPTNGSUMXHBQKXEAI","IVHTKFQSGPFUYUBPNRVH","LHEUIUHIYHQHEACRHULN","JQJKMNZBGVJTCNONKVVI","ENRJPTAWOLKZDVLPKLSQ","IBKMRYZBVWLZKDIZYKYO","XKOAFZRQMMIUNSJESKHN","HTNTYVUWISLFCZIKABAP","NILDDUJVFRJMKWHITBGB","URJWSRGVUIKITVLWSWTX","NCLZASJUVQXPJGOCZWXU","HJEAGRYYNRXBWICWCMSY","EQPNWDRWAQSHZWJGNJEA","CEDYOGXRUPRYFINEMFCO","VUXXQIDDRJDTNHUCPRVJ","GOJOWYUKDWABQZYIHDLA","MQUCZOGOHDZNTKDRJXCO","TEPLENTLSGMHXIJYYRPF","WOUPBAGKXIYTNQGTFAGY","ISFHCQGCHVHDLESMEAYD","LZYAPFTUHZSPUZZYPFBY","CKBNOVCUYAAJBYJQDELM","DFEXFDWWKZVMJYBAWFUU","IUFJVOAAUNNXSTXZWVWG","UTUFRXFPDALLWQURGUSA","HHYCAXBYSZGOSATMXZDA","BPNZFIRMCLOMSOQULRSF","TYTNAPBXQFARUNSBXJPC","WEOQSEKEXCLSCFGCWHCM","MEFITXKRJZTFFJYYPIEO","NPHPWNUSWYGLCNTVNFOY","HHDMSDMHMQWZIFQEUMZQ","KFDMVZKIEYGNILCAPOKD","HICPNUTHJSZTADIVCSFI","SLYAYADNQPQXXUOMRITA","CUTEXBZBVEMORKQQMVFC","KWAHSOTJYOJDLFHKIJME","PAUJMKZYGEASCCCVTXGR","MQWXXGJFPVJGXDRJQQHY","XIQBMSYFQFXEXVDUBMBS","KLBHQSRILAGKKXLXRMCJ","RBPQXSKAHLTRYUAROTZZ","WGJGFXDYJIICJXSISEJZ","RESSYUJMQIOMQZSXWYWH","GGLRFFAZJJADNSVNPGBF","QPRJRJGNJEXPMIHSOHRZ","SSEHMZWBHXIYPZJGLPVU","WSKIDTARCUSUMXBAYXCG","WKGNMPTXGRTCJFLOYNHA","HAWVXZWXYAFVMNKYCEXL","XTNIYAXXQEZZEWVDXTDW","TITHWDGAJFLGYBPZDOYT","SXTZVQETJHRCSKLONRQZ","ZCFZFWYIKYEFYXGTNKOY","UHCMRNCHHSIGWPHDMIMY","GSFERLAGYQESAGGTTKAC","EKIDASGOCUMIMUPDFRJF","JPZJVFDRRFTYQEBSWHGY","ESIQOZWUSHBEXBPSIULA","CFYSJBMHISHOMRHBTDXL","KYRHZHCKBNKFUKXFLLMV","DVKQNRRIWQVIONSQWUAZ","JKFEWELJQYGTTSLILCQH","SMQJBKZXGZWPLDVJIHSY","HYRCRDNCHDMCRELUOMRU","LQLYTJHBQZBZZVBSAOXJ","UJLNPYIDKBZXTKXPTESL","FUKHROZRCWAYHOOWMYBZ","BAYXLWMECESIACPRQQIV","PLVYZJVLJYMLZNIKJUQL","AIVDNMUFFFAUQYSRHPCR","OREPEMZPIRAKCYNPMKUR","RXLJVGAEXEXLVBCBPDQX","VTKZRZQDJKXCJILEQNLO","SIBPMERBHJBECLDVKTBW","GYARIMWZZJNTRQJDUCHE","LIIQVONFJODPOEHXSFYT","ONNHDYNACUENCOFXCTEO","JKDYQMXITVDJIQRNQENS","ATICKNBMGHAQRGQHUNRO","IVXSLQFEUVWWOEAYSBNA","JPQAXIKSVBGFWFXKWDOS","AKPORPPJTELCTEETMQLI","STNOANAWSOPSBGISXXDQ","DQUZUZSHPFRJAGAATAZL","RODSWMMTLRMPHGOCHGLX","NCINKIPEJOPCETWAHIWS","BIHKOXOWFZVSDDHOOXSZ","LJBQCXQJHOEIWNSNLHLQ","IIJMNSCBPWABFBRKAJVH","YZPWNKJYRWQBEBNUURVJ","NYKTBDFCNAJLABJPLTPE","RFFYJVSDMNOCLZXNECRR","CAEEDOTOJIUAQAYZXQEJ","GSNTTKIYMZPPCUTFKPUT","XQVPQUOPMSZULMOEZWEL","YUCAQYHANDVMUQCMKQCZ","LDTYRJCQIHCGDEIVCPVR","TSEPIGBVYDUJGPJYZOQH","XSPAZXVBOSVJKZYSHAPF","FJROZAOAOEHLXWNYVKBL","EWVQVVLCXAKFKDTLFHLU","NUHKQXKNHMAOIVEETPIQ","QUVAXQNDZYZNSIZKFKZP","WZDEXHKQXVIPPGPPWESW","CTLWBKGJUHYSGDZDMJVL","GEAWKPNITFGXYRTBEBKY","IKTRNSUABQLKWMGGDVQZ","AXYAQUDUXOVGAOZOGTQJ","LDTHRBPXWGWYFWAXQESO","UNWUDVKLQAWCEQLXTDUS","JSQQPTNFXHVTWRNZOYKH","AJLEBWEUZYOKRFAGAQNZ","XJSUCFVTFIAGRLKSJQML","PBVGIYOKODJNOBHTGDMM","NOSEBEWKXKVMNTUVRKFH","NQUCREVAJJOWXICYMYKJ","IGXWBRTSBBBRRXTLDOLO","XZKWHOUVMGHXMEVPYOHB","RKSLILWLBHAAIMWPBSMP","ZTMNAHDYYMBPXWCFHYSL","HULPHKGKCTZBMOROXUOV","GQNFMPKVQFIXZWNIGVUK","OWODKFRJBGFHYUNMLZJB","GSBGQQQWLLICHWFTDYCE","GJOGDBSRCEULYVTONJMZ","UUBDRIWWIZBPIPVOSQFW","UZHSXAIKKULGOOKHYGEH","FFYQWTEOLJKHKUZJUHWG","DHNSYZBWFFDNMBDIXJYK","ULSGFTQZDMGGVVYTUASZ","HVOWZTEYCFIYQAFVUXWX","JEFGZECTGUVPPLLQFSOJ","XXKPZPMTMISXNYFOEHKM","BFBTSPJZJALGZVXYMJUA","TMZIMEXQMHCPOGIIXUIG","UTOTOLTCWNCPABYMFXFT","GJJWPTEMNMSJHGEXTYZP","LBFNEFCKEJFKSOGIIMWX","ZRHIZLGTLHIZJPMNUQZY","ZFKSVSCFFADGRKORXWMJ","EUIPKWEGPEHQLTKIMMOR","PRXIDNZCKLLQIVFUUJCL","PLBAFMJRAZKRQJAVWBXI","NLYXIFTEPVPGHTJMHUDJ","TNBLWBGUCDFRQFQZLJFC","FVIMQRAXLFGGSJRQKXMP","DRGTXXUIGAMNXUBPOBMB","GUIAEZSQZFFCYOXVLUFT","WTJVOKKCMYFUSNVYNNPO","UUQTIPQVLYRHRAEHMOLA","ORVJGSHTHWHCTZXDRPZC","PSMJUSQGJEHXVCGDUOXD","MGFFIEJBWKFLCTUWMNEV","RLSOPZRLPQPBZWJJBUKZ","ERKILHGXWKSPWMFLNYXC","ROGQKPBNJNMPEZXPIDOE","NITLVAZIYYNPMTHYKKMT","XAICZHTHKKNZSINPIMAJ","KNYYIIWSSINQJXUKEPUQ","ZHPUSEJAQJJCYKAGUXAM","HNEQKADOSXERGWNYCXZT","IKVHWYNQVQFCDLVOMYEE","VLXBJLALKBGSNCBKCRCX","HHBKVWAHUFNRSMVBZXML","ATGNXHZZYCYFLZSGYSPS","ZEMRRJSSGHEGCKVBTVCS","XAZIZRRXMGSLLGFEPXWX","GCFKOALIVNCUNBDPTWOH","CISNQXTHXQEFULQLOBTJ","PVGEYJVTHMAJUTZNSSUR","KBXFMNQAOLMFISMGDJAK","VCTSVUFQNZHXCECPTURK","HFPPZDYCNYOIAKAYEFQR","HXPJETAXQUHXBZNBCLDR","LUANECNKKDCRBTCFOFEG","BMECNTDPGJJRDJGJNUTX","XXQASVHJAMPBATDNOJEU","SNNVYWGMQZLPXCQRZXAZ","LQCLLHAAQFWKUMHTINHY","NSNMWFDVDEWOWACHKCJC","JGNESUZAIGAXAPLZVQWA","UVQSVSAFXJKGPXKJRLLB","RLYSBLTYCPYWKORIJRPG","CZMUWZDQKPRECSYDDRDF","GBETQVBBOQHQQVKOWQEH","FWNHOLNTEQZKUDFMAGNO","XWEPRPDOFIXMGKVWXKPB","DONZTTLVZYJYUQPNHVDO","DAALMXHJKWKNNAMITZEU","ZPVVFMIMHMAKOCVBAEMK","BZZQZNYUMEOLULGZYQMF","EOSTRPURUIDVHELGRLAF","QRQKCYJCQXIVMAOFPKYJ","SBGAHTIYFLDVEVFGVQLL","QTGEVWJMGHWBKEDRYLRD","YWACTHLOXWBPPKTMGEYP","NWQXBTQZGJEFHEJANUQK","QUCHEXTKCSZPQRPRKHST","RYAYEJBRETEWNGGRDZEF","TFXKXMDJTWCMUENZOQQU","JUSZCYSGAWNTCKFBYJKU","HPIBTXCJNVFZRYYUWQCY","PRUTEZUCKGYRVJVRGZAU","UGVOGVKELMDCDXVJYROJ","AMCXVXOEZRAVZVJFQTLD","HOINNDWMXKVXZZUWZLCY","CCTDXFIPYTVIKDXXIVJF","GGEHGBFHMIFQKYTKFDBG","YWOKZLIIGTPOCWXKXDRL","NWDXWYJCBLIBHYMJLWTT","RIKTGHDFMUQZSTZRTITU","TDYDBMMMIFHZPRVWZYBN","VUNPPMGJWZFQEFTFRHTB","OBDDUYBTYFJVZYLQMRZI","RHYVMTDEAYHQZKUUKXPJ","CAEDYRWKJXTCETZTNCZP","BGGCTCYDZQOEQVHPMFZV","DUXJOXCBBBSEIYHBAFGC","VVGOSPDEVECYZBHNYKQC","NIGXJNAJVHLSERGWJLCE","SEERGNGGZYINGPKPELBB","UMWYGEWPSYVKDZDLMJRM","HCBPTLHZWIBQWZQEDMTX","LQHQPKDEVUSEYTUREBRD","LUVHTOMYAHWNYFFPQITN","FLSDGOVLPOQCINJDBXDC","HZRFHXWXHSMMFESMSPZJ","DPLNCXQGWTIDVBKCAHBI","ZNWESOQMDPWIGJVLILRF","HBICCTEDCHNBUJHOAYBD","PZOYKJLTVCYCFGGHBMMD","TZGPLOELOHQDIEDSOOLL","QJPXSXFVJTBCVHRIVXTJ","ELPOQSHGJSTZEKXYHETQ","ZUSUELCZLXLPJCGBUNJD","HCFLMEJVKFLLBFIFSMFD","KSVVUBYQOJWVNDJBJUWT","ZHEBMOGEBNKLFFIZGISU","RORERAFAVBVWKBZWQGCR","TMEBROCZWUVNKNRDPYDM","BALLEKJUQLNMATPTHRTD","OQSYDJCVJHHKKSVODEKV","RXJTQYPZSKCGAUGEFKBQ","UKAEDXUIBEFUDPQTNFUF","PWNPSUVZGWPAHPEMMYWP","EBLHSBCIGWNVUDNMZILF","HCIOROCFNYWTZIBULDCS","CRPWUCLVNYBUBJKUXMAM","KYGLGJFSOJMQBDPVIATV","AURBFBWEPYRZWZMFKUZY","DNREQICAIVVKROMWRKCG","KTHGUWNEQOFVBYCUGGUQ","DSAUGMSAYUGIQQRMOETE","TYBWYDQEJLUMDUIJJALJ","XUSPKJBYPUEKUFHULXYU","KUJNRRZCUKLTEDIQOJOG","GUQCCZXNZVJJSSXJMWLI","IWBNCJFSUUYAQRFSQCHP","ZRZRLYCZUNHEMIROTXIO","THQLAVGQXNIZGJQUHTTD","IDHUNZKHYTVTCLECJMUG","ACFINYCUTYXBBFWOGIXG","BUZFIFHRSEZUIFCWFHQY","FOBITXYBIWHJQIRYNAPH","EPDNWGJDPBDUPEEKCCNM","YUVPCOPSPHBTYFIUNRZC","TCYKGCXKEKWFFUWJILBX","SDTQKBMXVNBQPZAWBZGH","KFMRZIAHWEHQJAHTDVSY","JTOYURWVQFEAKTTJDWSZ","ABQLBZGFWYFFTUGNLEKB","JOETJZENVZMXAEIEFQJC","QQHJKPYVUIZFZFZIEFXA","EMXHQILWAWYRMHAXZZUT","JVYICZTHHQJNCIUVSHTT","DTKQCMPBLLWXJVHLWASD","TDTXMNSEVNXAGHSJUHKH","VHGEEOPCOKIHNBFZQZGN","NDOTNGEJQPSNYZRCNIGD","UONIPUJGTPVITJEISITK","ZLXXKQBZAIDVWQDOKMWF","EROZBUHVCAFCNEBAWFZW","PETNWYBINXORREQUYZPC","BWEOCIOYPQWEWSRTQVBD","URWLXMFVNWYOSEFWOVWD","LVHKNBDFWGJQYHCXWJTJ","GTAAZFXOATTOOBYBCDHA","JSQJZUHVECHKVHKWMJKO","DECRHCVLFELPYDYZYHXE","JEOGLADZKPPPVSIEUDRA","JERHIRHIZEMKKCTXEYYQ","PNFNHORETLGFPXMZQVHP","BVCNZXKGVIWMYEZFSTJN","EPSTOHTFECWGYATZXGFU","QCHOGIWABHPFZKZNRUUV","WRDWTZWRFDNVFWMNFIPG","PHMQRLEKHAHDRLALKYER","BTMJQAYVIOBAVNSOAYYH","ZFNSQPFCNJTQDIZVIYQT","OTVLJNZJMXTLEIDXXJZM","UVCZFCUNAMIQGFBPVAAH","ZVUDDZCCKEOHZRIGTDTV","RELXJOOEOPNPKJUQLXSV","BHECYNITSDOJJBJTPXZF","MPUZYOPJNJHOQLSQAAJS","GZEPANKRKMWZBSABJPNW","YWNRJFHKIRCOSIFVVSMI","ELJHFJIOAXLYTYRDFZPN","SRDKCJFXDUHHHQOMZYBZ","YOATOTWTULJOFMBHXGGA","COJJGZYIAZJYPLRDFQYZ","DHOIWPRVXYYCOHLUHLEJ","KOHZZAEEQDGWMUEKLYGK","YEMOLAKULPDYDMZCPGJF","LPDXLIIYIOIGUXWFZGCK","VHKYUKDJQMQBDUAOEKMM","AWUUTQASYEFULPUFBXQT","LHWODXCJJQXKPREIJGDH","KKDWZYDDXWWJFVXISCRB","UOLJHSUSYXBJHHHIFMNC","IMNNHNXBRQCLGQXNKRHI","QLTZSCJZPXDZJRPSEMTX","DXIJNHZXAIIQTDRNGBMX","AQWLJLDPAWMFTWQJERIE","ASXVWQJCTXZVNXGYJLNL","JZQFYGQEYAKATHVPAGTT","EUPTTXSEJHPUJFZHORLM","SVMLFJCFQXAWTRRMPJRA","TGUCOWJCNWOFTCSYNWFD","TGBMZTZOEQOXYLBMHKOW","IEECGWCUTIZOQDBPWCGA","UWASHBFQOTPYATAGPDCK","NEZFHCWFECHYBHSILXBZ","TQXTJABAFGNUMMZVQXAU","CHUDRONCMODHGCCRCDSH","LHBXVCSLCUHEEDJVRWZF","NCMTEOLHUFQFOUFJYXUA","UBGYEPTVOSDDUPWAGJJA","QCHEWMNWMJZGKFEQXZON","RRQNIOPOAZQSBAZZMOXY","YWGKEMBDLRQEIGTQWJHW","KZRNZQOMELMCKVPOHQRT","HHZRPTJNEQMOSDDRTRFX","CUCOPRCYJVTQCTJTOSJS","LVIDYLWRCEOGYSVPJZPS","VJKZETVSOEMZZWEXHAOL","GETEZQVIQLDNWPMALJUZ","NIAOEELNGBYNIRTHKRRA","EWNAMBCZLYYAGAPKGAXM","EXBMQXVAOOASLPSZTWYG","UWGAYVMEYLSCKUQARNBH","BDZOVTNOPLULJCNHYZLY","MEAWASYTHZAIFBXAWMON","YKYJMLRMMEKAKMYMEWFL","WHWBIVDGHRTFDRPREIEQ","OOQBBONHNTVLCRONORTV","KNDNEUEJCKBSBUTCKHLX","CGIEZWTNNNLXAOMGKTRO","DTGEPAIZJUXLCHREGLTT","AETAUHIEAAUGVBKKDVLM","RIZVSSZYFVTFBOHWWQCW","QXENARXDMIRFTSANKANS","XGXYVFWTXZRPYWCANBDB","LWGGOGTAIGSFPQEMXAFU","BWLBSNBFQGGBCMIQVDRD","MLLDBRPARUWVQHYLUAQM","GZOLNYBKDUORGBUJSJML","DIGWQHHMHZZPAPAQPEAS","YQKGRESJOEVTODRGKAVT","AWJCLLSAPTUQJEYBLQMZ","WJUNNOTZOQVOMERZRJZH","EWZQAXRLQFMOPJBEXXDL","NYCCEVBWGDFLZEBBDUPT","ZBKOMLULKYXAYZCFWFDC","KINJOQNRKCNMFXCSKXDX","VCXVDBAZIFCTNPEDIRXS","TMEBJHTVEYSBDPWGSZGB","EKUUBYZJSWCLKIOTPHPV","IJYLZXTTWZUCJQYNRYWJ","WYWHJLCYUTWEDUPETJXP","KUUWKUJDUFMRGLAPYEPS","YNXDKOJDZGVMCPKPLVSG","AHZISZZQFPKFEJIOATSZ","ANNEEXTPSOVVVUFNVFFB","WPIABTPBMHCOUQTYPOPK","CLHXFMMDRRENJMOMHFNU","MPIIHBIZQXLSISSQGETA","YZNJNDVVIIPWZXEJBMIR","KVLUNDKVKDVIELRSQMNB","WCXVBEGCSQVELJZAOLWY","RTGVEZNVLCYJGVFIBNMU","EKYPTZSJLOICHQXOQNLD","PJNWEUGIHSCNECDXCVHN","LRRUHQIZDVFVESTLOZTX","TVLYXOXBLGQYXHUHAFIF","ANAFHTQVUJVOGGOFWLHJ","SXHPHBYHGHMJWPOEKGBF","PWVXCJCAULJMJSESUEZC","LNLICBONHPSYOPVSYATU","LCHWXNORRPVFDJPFKDSS","UMSKBODBQYWDCFAZSQSL","IOSLZHSJMNDJZWTDMYEC","YCFBHHABAVNIJFTIPLTB","AXMCVIFHGLLFOQIXAIZA","DOIOVDYKQUORTATOIAVR","NGYDYGBYQCAUQIKLNLWE","FMXYMQOXSJOFRMJRSKSI","OSEEDRPQCNWJZTHOJVLD","GZJZLSQFEINSDUYGLNWP","DVYCOHQAEDDKCMLPGBUM","MKEPGCVRSTGVOGZFNSFR","XIDAXOPDRMQFYWUEBRVT","NDQDJRIYLNRJYULVKAAB","OSHMPDQQVNLISDNDUWBI","JSTJOEGYGHCVZLJOOAGL","PRVIWJLTFNBQHUAWYGUG","PWBPHLFYNOJCHFKEOYXV","LYLUUNQUWNALLECTRITE","WCGDJTJZRGUEGIYAVRWR","EXFPBHKURDYPIGTRZERS","LLYRVZURQQKWNPNQZYKQ","DKGNRBFSFYNSLLKHKEYA","WKYKAMCBMPRPBZDSCKNK","IACTLMAYSAYPLZBNLFQX","WHOYJTSLDFVNFAJTOJRH","MRYZQBMDICAFLRFWKXKQ","FHDMHMFWYYFKSFLKGXOQ","BQXOHCLUCXKJEPVMEDIC","BNOTUZGAYUSBMQPUUCQY","ZCHERDSXGABJPPFJQLLQ","FFRTVJNSNFQPHYTBDNYJ","PAUERZPKKCARJULFFAZS","IPHRPCSUPTFEVAKOZBYM","FBFPVSWCVVWDMGUEIPYA","KEGFGTTHWUTEVBTSVRUQ","MSVAYSGJHFLTLTATMVAL","PWPMXKEUBALPVGPTYYCH","FNAQHALVYLINJXAIHGDI","JOZEWPZXPCEURHMAJXYH","IGXUEZCNFFYQTXWSOWPD","YVXRCJUOGSXRYUNETPSB","VSTQPQIEMZJMVJFZSZPB","RNUSJHWFWQITIBMYRWEF","WNRRWXSRYIUQVOIGXGLV","XTRFVDDOZJUVZLOXKHOJ","RKBMYJSXPGTOZKUWPZLO","JFMKSCHDLYOCIPOJAJGR","RBGQNANCBYTMFHWXJGAV","GQXOFOZHZIZQLFIZHVDK","VWXADVAPDAKJTJAYZZGY","JHQVMZUVUZFSYEUBCUSF","XCPQOPQNQYMAFCVTBROY","QWSOCMSEHKKEPBUDSMSI","LEIQJDKMWAMNYEDDRXHY","KTEZWAEOMWXXDHQMLCAJ","CNYDREGKBPKLLOMHQQYD","NVCQCSEPUGBZTZENDMZF","DKSOAFYRVWUKTYCXRIPL","PQMKRQXVCXCGJUWJBWAX","UWJNVMNOUEBLUOWLEVIJ","UMRDHNNIKPHEORUJFJZB","NANJOLWVGFEBRVGAKTLU","LUBZNXKSGJWVJLEYWAVE","HZHBWOBGJMDUJGTWDDPL","MNGYYMWWORCWSKXOAAWJ","PZEYFXUKDLVPYDPYPNWE","EZCYLBOLBLUSMYQSYLEB","YASZDIZVVWBCXFCIGRTJ","ENCQOSKOFPRGPJFUTGRR","CSVZZXHFQCRUSTLGNVWV","KNBBYIYSQPLTKIUJFERY","GISYDFGSBCNNPQROAPIR","EVMQDGAIKRITBBTEGAWJ","EMZUCQKFHSWLPIESQECD","XLWYMREURCGWOFSTXCYE","WURLEVFWZHZYSXWGPCDI","FJETOYMNCKRYGILMGQJF","AIGSICBZHEHMNOFDMUQP","GJPPTBBZTMHTVNOFRPEY","VLKKBSPOOHFWQULJXPLT","BSOYHCDYTHXQVJAWBPMR","WROOOZALOLGSFVQMZUKV","DJLYVOVYFHQCBESPFSCW","DJOKGEWHAJCEUQCPEZOL","JGPMKIBRAFPGQDQWKPGK","YIQUAVKGUYSFGHRQRUJS","AZASESROHXBHHRCIOMOL","MIQSSKKJGTBIUDBZWSPF","PQNWKPGYDXJRFCJXMVHU","QKDLOEMMYBRNUELEVSEA","PORWSCUGXDAQPDDFJPRH","QLWKRIQNCVNTLFPDJLJH","QLXGPALYRFIHQEUHMMWQ","HKJURBXAMIJFUILLKYLB","DTLVYHDMTBDDNOXEPXHE","FSJBBWMNUYRATCVRLAGE","CLHPZHUREDVLXGNACZOW","ZFWTJUMUUUAWFKMHRIYV","NVIKBVLDXBBYGATRUGLO","CLNIXZROHRLWMUGPRRUQ","SVPAXIRRQEITSVBPWUGF","LRBZNHOFBIVVFMYFVRWL","WGEODHFZDLEOFFNSPDZS","NXNVJLAGDWSBFYRIIYIL","KOCRURLLVLDKKSFVGFCL","EWMJWFTEDBSNSUGMLSZI","FCTPUYMAGOLKMZVJEONI","SFXKBGYPYXXDBSUVTIYZ","XLJJNGSRUIBOPBYTHWIF","VHKWAGUVOSUNFFZSLTMH","BNWTQUMXTWEODQNFWHAN","BWCGBBBOVNYYCURTQFSL","BXCHNPMMWPBXLDDPFGFC","TDCWXWRQBJBFIFMYUAMQ","PNPDQVUXBZBVDETCAMUB","XYGIDUGYVUQMHIPZDLXE","LYBQCWUEKRGIPOSUJAUG","UNSBVKAYXZEKAICEEXJP","QRZHHTBSTYYNLTQGFQEC","SINSQPYXOHOEAPNIIPAB","NZQYUGGZYKBQUQKNGLMU","SABTRODBFDEUEUUYCAXA","MBTHRFWZQIWLKXGDNJET","MIPTEKRGMRIZUBINJENZ","OJMAISDVBHQQRGJVSCDE","VLFPNNDYRSXHBMHJEKGG","TXYKFJHZLKFJWLYLYDJS","VIBYUJJBVQJRPHDWSLVD","XAMVNNGMSRGQCHOYSYZO","QKFHRKDJVAPVCDQQSZEL","QKDURRTKRUAJFHQYRTKP","TZKYEAOXZSKSENMXGHHA","EJJLQCJIVTXRUJPBJFAL","XMDBBRAHBIJFTVQKXBUU","XTNREEUNJUYIGDLHVMRW","WADPXTBUUXPRSCLWHFKS","CKBIQMSLYJJWLMMJHNFD","NUXFZICIPOATYDCOSWBQ","HMPSABDJQJNDFMJGWLQL","ZTFZWJQOHTHOIWGIZMSP","XHTCTELPRBCSUJRTUJHB","DQPNOYVNKPDHYYLTEYIV","ANNWYGPTQZUVRKIGKFTU","XYDVYQPEPZZROONNVFGN","GCKXOUDYZZUWZZUAQLEH","MGYBUNQRSYGAASYPMDNM","EIKGHGGZRMGGUGJRWZKQ","XRRZJPOWUEKZMWFVDNXW","BFCWMLPIMZAJSRJCIZAD","DMCRIJPNYMKZRMXFAMPM","OQYGHJKQIKTMYXFHGUWG","GGHYVHFVTVJJLHQSQAIB","NDNLAUUIPRQVXYVSFBPA","YZKJICBZCMAPRPDUJXEA","OVWOVTIAWYCUZOFHQJIT","VKKOZNILNPLBMJRHFAJB","ANYZCDISMRNJBAADPKQC","ZBGLNXUSXFVXTTYVZHPN","YDZBDZGULWXLYDYNCVFC","AABTWAQVHGKHJJKOKRIY","NHLNMJAPGHRHIUCEUTBD","ZLMKXXAJQKHFSSVGEXVM","FOTNJYTFRWJSJXEGUGSM","QBSKWNRCMOORFKGQIBVB","XGVHEZPAHHPZLHKHWDLK","TZCAJKQTMOUJUPQAQIDX","PSXCBJJZOWJJWLKHWABK","QXTNPMNHUSHLKGQNPBMF","YWOUJADHBERTENGVBUCV","OJIZPAMGCBNAXCUICZQF","EHZKUHFVDJSSTDTKDFTF","IGHFKDQNDGUJNVTKDYHG","HCACHTPMBISJOBRZFHOI","NKRCIKONKWVTAWYHPNTQ","XNALPTMUACEPNVRXHGKR","EFMEBKNTZIJWWLKNEWHG","BNVOINNPVXIBCWFGHUBI","CKHYYRNEPULQJIGRXTIS","QQVVNADWWEGZQNZQENVW","JIMTQTKOOVIHLECAGHYF","LHEDUFUBSRXEZJXPEJFT","EQASWEUELVJYCPBWVXZP","OWTNGSFMCMHIEHACNXHY","SSYUKCSHZSWQOSFWKKLM","ZSXFCXIPWRQOLOKVSDCU","XZKLRPKDCVSDNPIROQHL","JXZVNMQGPTAMUMZNBLQF","GIIWXRNOJWZTTAQJMGPD","BRRVDRKGEBMNLWJLPYZZ","VYUQAKZNSQQUJIROBCVH","DJUQHDBXECYBCURDGTSY","LISXSKLVMIDRTXJBDNYJ","PYKUSDXYYPYKZRHUDURR","DWKYWTZZGZIYZUSRXRRY","IQIJJRDONXFSTPRPKQQT","SARRULLUCCSMUCVFVBTI","YABTRULCMBVECOWYZJSD","NMPIQMNLPJWPJZJBTUDF","XAMBOKAPTUSGHJQZXELN","PJCYINBDHGIHGWIWGILZ","FFIOOYNMEAZTJDURRXUA","EFHMBQJIAWJHCTVSSJEW","JFSTJOMALJCROKERCPBE","LLMPGJIYSMXEURZFFNFQ","WHKMTOEVFFCSSOIZXQZS","EWYANZFUMMLLWVXPLBNQ","JPKBFSAEKCYRYYROXXIM","LVZHSWXDAMVJDIKIANON","PNEPLXDLWOZIJYPCUOHW","AFFFNSNNHCAYRGNEETPA","HOKQMASJQCFTHNYUHOJO","SMMJSZNYSDBBTLSILMRE","OYXVNVRUJBIBPUMJWCIQ","FJSAUKIIYBMNCLKPICMS","FUVWRKFPMNFTYZTVJEFK","FTXJEJZMNNGSJEOAOURA","JZVKYOHKSMUAFTJLCKZQ","XGKHMZJAVDCGCXSANZKI","LEKSZTDCGFSDLCMXDYZA","BDJDABFPBQXMWHHYDMAJ","RSOEWDDCBCCEHLJJNOZQ","GYEFILDLYFWRZKWVPZXS","ECWNNHXCYWSGUXLEIQPI","XLAWYYSNZRIFTETJMQLM","MESIDGNNWEWUSYSSYKHX","EPDXUWIIOUUAAOKDUZQR","GONYOFQMSZKYPPXLLGVZ","ARBCFNFAPXTVOIVCPNRJ","MBHBQFODLJELAHPIWWIL","TBGJLDOAQFKDGREYWVDJ","EJWHQLPMHXADAIMLMALC","FXFNPMNNHQXNZTURFLGM","KIPKQEXCGLHOIOBZARNJ","JMZLFVCMHKBTSSGJWDNF","QWTZLWANNNXXBYIHTMVC","XWWPPCANHOSYKNZXKZLX","PKWQIEZDTVGQTEHKGIAN","YSNKIMISMTPBFMRNSTSN","OADJELUKVUATONFWANOO","IGPNUICOBVCRVHBAUXMP","ROKHEQEEDUUMAJBWTELX","BNQWUTYPQNEJBRRFHXLM","RFAUQCQKIBJJOZFLTGAJ","TGTUXMCGJNTCVTWLXNXF","QGOFIWSBCUMVAHRATTIE","JBHEXDRUSPAJXQQFMIGQ","CVLECFGYAPCJQJPPPHMH","YMQVEGDROLHSGVXLCDJC","SLOLXFCMMOTMCKKHQNAH","YJZHEYSIEBLWOBJLGOZV","CTHFFROVGOEHXGOEEIMI","JZHZASNHGMELFLSKFGIN","UOUTUKXBSMLDLSDONQVV","CZGKMYUTGEHCTBWNOVQG","HCKTUPHJFEFJFNTTOQNU","UUZNXVDLQTSAVETSTCDA","GIJNYFGMVTIRPHHNEKAX","FUXBYSVRUYTCJFPHKVVH","RFYIPHVVRYSXSRARJXKD","VEFGLWNVUKELSETHMRCF","PXCJOEAYBNBZTJFEFVBZ","FFMXJIGVBJBSGFBWMEUP","RYOKHUQMRROYWCWHKEFL","NGDVNFSZJORCMFMTBEIS","VYRTAPALTFWJNCGBJACS","PVUBBIXEMHXJFQCFHCQC","KPLXTUACUFULAQPDAOIO","VHXAZZHGDAIPRWNKSPMO","WIAXARAAFKOARLCSMJYR","JJHCHWMZLAPKIPHIIJKN","WAPNLRGZDGTORARYYDZL","GPVOGCZPOLEKMUZZNHZS","OUHHUAIUFHFLYBCHFBYT","MCFAWFAMOBEEVNMRNULT","DQEERILZJJSYNAYMFAYV","BCAYSMPFIAALTHPMPCLB","NGZBGZNNANIDRICJWRRE","URQNYHBQKNRZTQABRPOR","CWXUHZFDQWIMOABOHDET","SVTLNVOHNCAPAXLHWRLP","NTBDTDSCGYWYURLJMZQZ","BRRBQELNVWCLRDOMGIOO","HMMDDZOSYHTBAKFQPQDM","MHXFLORTYFIHSWMXWBPW","IJAITFAKXEXLNWQYMHUL","OEUICHGYIVXSEZCAECMD","IJOWIEWUNSHDWCMZJSZT","PYLWXPYBRKGCWUAEYWAN","PIRNMDMXXOQOMDKKSINJ","VUNRONVPMXEDHVQTAFQZ","TIOHLARDJHPEDCXRSSIE","RPHZMZSNELOZVEHHFAMQ","HDWKITEANOGEDNDQMYFT","LTSGYBPDCCVJFRWPKAPX","QVBUKFKZFRUQMMWKOMPS","QKDXBZNNBEKSAMOMTANY","RHQDWMQMYFEQSHOVJBJK","FVEHHSUCUJCLRSRNHHZF","OFYIOMEXNPKSKQAUJWYD","HBRYVINCPOKFTIOKUSHH","JTBTKDPVBOAJRRHMZXPQ","LZWHHMRDGAKPUNKERABS","QBDHTLVUKKNVLLEUXXXD","YJUUZEAQGBKYCOFVBDSL","PFIBQNXNKXSKIMEHSEXZ","FIXIYFFZIXMZCUAUJAJU","XBEFNLNIPMHVWGFUNKVX","IHXMCZHLZQHWUOEJZRRQ","DYNAHSWUFSUNZRBDQKRQ","DAOXOSGPLYIPYVRHONET","HYIHRLMJWDBZEQYUKEMW","EULFPEOFRSABSIIJUWTS","AURGMPAXVOTCIGHAKXFD","QGEIQOUKLPENJVTWMVVK","KOMUUVUGSAJKGOTYEPLP","EPCPNXNZTIJFWXZSSUYN","WIXCYSCEHNUNDYDQWQRR","ZDWXAXQVROINYFRYAUDH","HZVMZACXQUORZMPZKFUD","VETWMKWMGZVQASCASHXJ","DOACARDMYYSUELSQXOCG","QYWQQAQJJQUOEWQGOWVM","WNIAAARXPTFFTDXKGQVP","GREMNWUDUPQQEAREBKES","FJZZPWLVOGKUXQIMPDQJ","UIABITHLDNDIZEHOBUJR","AVMZMWMDBCOYMQZUJIGO","WJXVQGJTBSKDNWFBVRGW","VVWHLVDVEJJCVIXLRIES","AOXPNCTKVZIQWFZIADFG","OQIJZHWQPAKRRHJGKCQF","DYYADZKGEPOTFXCGGBYW","BINUSWAEASLGRLGWLQCP","HTIOSNVYOVURGKOAIQEL","JRRCDXAQPDHYYSMQHJOX","FLONXENHVTSGKJIPIIHZ","NPXLJKDQVSNAFDPCICJF","XCLKNVZWDJVTAVGJFKZA","EMDJRSNZXYEWCPGQMIOS","RLLRGTALFBOLPTWGNJGM","KMJMEPEQXSIQEVHKRJYW","KOKZHGGUSOHCCQOGHTXH","NHXTDFEUOESBSCCBJKXD","YEFBWVJGQGNEOKZTRDNI","JHJDKLGVWEYWIDZHAJPR","PCXFMWYECNMNVXTHIZCG","DAFOFEXFNMYDOXKCWLGA","AUNVTIEEIGKLGPZLUWTJ","IRMYRZBNKJPMEEKZNODV","VOGBFIPBGKLRBZPUYQJK","AYXGFHFSVJNSZVUGFLIM","VVDYUUVVLEHNFEVKNCCL","NRDOOZVUMFIHANIWHDRU","JZHOFEYVHCGWTLLILGEX","LOHNBRJKWDFFCOUJVUEE","XMAQYLALTGKEUTTXKDKG","GROKHKVCEAGBMHUMUUXO","DIUZBOZOTJWBAKNHUIKZ","ISCXBWJWTJMYTGXUWWKR","FHSHTFRQODPYVTVXSHVL","SHJLPIHMFSDMBYUUDNKT","QBSLXPKPYHCQOLBGTLSA","FXNGVJCBWPUOSMZPEMEC","TGTKTWQPHKPOHEUDPZGN","OABGPDWTPCVKLQUEPMVY","WLNERJJHIPWWRYFGDBZU","FXEQPBXENSDKDSOXBZGK","QCIHCNOFOPZWOGMGHJKU","CPGHJWELVKXLPFVRTLZJ","AAFRGSXPDJMFBSPKPVVM","GSAXYVQTGPCISIZACYQF","ICNJUEVLZTYFLYELTVGZ","MJJETJFVJXCRZRCVVAHV","TFCGDHUYCAZQJIVCTCZD","ZCWYTBVPBCMUHOAMVUKZ","XLQGUNLPRMSQORQKSLBV","ONPXDRKZOWALISTEFGTW","TOOJFETZSWUILLFPCRQS","QSFALZESFZRYNFIUMDVG","APONCVEHPUZFNFHAGLSL","MLMCTUYFZUNBLBPOYTVN","QUUFBBFHOZVBLHFEDDLC","XYEJBVXBQUPGOJNSLSZZ","UUCFDHLGLWJKWPTZMSAC","MRLDBYVOTWPNTSSWBDFO","BOZZFSYRNATZSGEVFZJY","YALTUFRWKWMLMLKRGKKT","KGUCMZXRYIRYLETFJLDV","HQGWDSPJEACPGXTSWTMW","BFXOKQWVBBRLTZHXSWGW","YJNEIHZEALCDQZUCQQYT","RPELONIIMQHKZURJDQNF","BSLTRFWJVWDOLJBBXLKL","CTXDNONTECYHULDMQBVN","XAEKKFNJRXUTSRWGIJBM","MBWINZUFCSVZUZLEGYNZ","YJSQDRYLCBZQDVZSWVXY","PUZKVKOCLEBJNWBSPADT","BDKGYLYXGYVYSXIOHYSU","ETDURHMIHQCKVMTVZRSF","PQFKNNYWOQRSLWMDDBNM","RPZMDSHCJCKBSPLFFLBT","BULORATUBHHUWGIAYRCJ","TMMLCXSJKWCLQPAJRTEU","ANOZTYZTQBEJQRXUQRDB","PFOIWQROKXIMKZNDXMYN","QDZGUWCKPFLFMCNISGYE","EHTOGGUDTSRJVSRROTCF","APKORZWKGVQKEJYKQSPJ","NIUIANAQIEWKVIYNIUZQ","RPAXZAJRVZAIJWSKLSCT","YYDUJDHRZIJRZJOALYRG","ZTQIPJUCDXVCVAWGDFXD","NGWORMPDMGLNAEWRNQUQ","PRSNSOTXTRCIZAXTNMYB","ULPWPNOCDKVTBNIVEBVZ","UZKUAHPPVNQRYHOOUESA","ONVRBDNHEKGZJQVJZKYW","XROXAELVIEVYRQPUVCBZ","OKAYAVHCFIAEBOCBUNWC","TTCNLSHGWJILTIJVESZL","AAQDQSFLHDPDZSQKMXTI","IBTDJEBPXABXCTBTNIGW","LXZKRPXDPQMXRHDCMEUJ","GVIJQLEDVMBHJBTDSSGH","IUHBCKGQOABUXJFPXJSS","XTBJWXMPPUYAPFBTPJJF","JKCIVHXUTRNQNOBJNNAD","IZDZEGSWQDBZPFKMNHHI","BWAOKCXYRADBZGAFMUBC","ZFEOKQBZXKJAGKOSOOSF","OVHNDJSQGWUFDAUNQXPQ","JYQPKFHYVCEJXNWBWQTC","OPKRQEHIDYYMWRDHYKFT","OLCMYAPXSKBHZLARRHAU","FAIERLNRYSKMGMAEOPDJ","BFQBQSUKAUEHXPNOAAGY","VSLBHLHVDLEESWHIPCUR","YZAVQOMQQURLMEOTRWRU","HXBZWKJNMEGNFGIVWWNN","QEAFIPACLRYURZVPMECY","KILRQWOPSCELIEQTVQVG","KTCDVXSHEWHOEVGWRULL","YPWHUOAPHXYTQAYLYQUC","MCSSXAOQXABVPAELQGDX","DBSWDQJDIEHWGAOFAFVZ","FYXWABKRKNQNQJJTBTXK","ZEGHGVMJAJIHHFFIJPBT","CRISAUOENLOORUVYRJHT","SPCBXILGZMBCEJWGDKKS","XAIPXDNQOUMILOMIYXQY","MRCQDAYGLLBILJZKPMBD","INMUDACCXVCJMEBPECYR","NZCAKBLZQMDYBRSETXIQ","SMCGSDYZFYQUZUVJWILO","UQMXHHDCGOSAAWGTAGSH","EKEFFZPBHAPDQDCZKFBQ","TVQUSZPUHHDMRHTWIKZR","MQUEUWFGEIZXEPTYQIUY","PXMJHFHPQHHEZDJVCOCG","XDFDUBBLJXLBUXKDETTW","ACBCHKXJABRXEXAZYDMJ","AXMXUYAYSVXUZYWHIUQI","XKIEJKDJQRSSOFPKDSKV","PHQPFOWPKOAIYIMHURQK","ILDYQUIVOSTECLVHZTXK","HZUIHIRBZKMJVRHNLRKC","JDGNQDVQWUCFTYNCGFFH","PTQMKZZYQJABPIPFLMXJ","GBOBZCDFJIMACEMODNMV","YOXNWMVJASSGUHHVLMBU","WPWAWIPZXBVVSULOIIAI","CSOYBXUMLVIHMEIIOXKL","AFJUBWLJELRGFFFHEZVP","WGYKMITBHFOKMZENVPWZ","ANIGUPPAOMPMSPWFYRIF","WYPIYWXVLTXMGFUCULCK","XTYQJWXJQHOOFGXFCWBP","QYDYFXBZKDLIZLAIHZRX","GHMNPLTTHUJZUOYZOZAY","ENGDYINFHGFPQRDHCWBL","SMLOCJNQKNPQCVWAEJFN","SKDIDGRHESTYGGMJRBZB","QQTSOPSUBZHTKKDPSUXY","PSYXYKIPNKSDALXODPIE","RSZBEESXAPXPHWPFIZWW","JOBMABCDQLJHFIKJMDIM","UGECEVJMUGKGWOSWPUBH","HKRMUBYIGGXDOBHSYQFS","YRYVFQTUNVEWHVLCYJMF","PJKGMRYKJFDIXDFEWYBJ","VFFFASJYBVFTFPZRIXCS","FHCCKHGGHJPFOXKQPTPT","QWMVMNPUMTORAQTKZCTJ","NKQCJASZVJULGIJUVYQH","TFZTXUFZYYIMJYOSAITX","UNICVTYSTOAMVBHVVNUU","LEGWCWPEGKBCYLEVFCOA","TQPQRWLOJHKXLSTPOKTX","VUZTIGQPKGPDYEWPDHGM","RQJCJFSZPNYKKAFSGWHS","EYYDFUUIDCWUTIZENRFC","GENQGUIMSRGXQECXYWFE","BBYUJXAYQFBZLQPRKAFF","RMCJQGGPENVFRTZCTZBL","HEKSUCMGCRLTDPDUVLLA","ZGFQBHSWIVKPZWKVYWCA","NPWTFBNCMACNIKFJRYIZ","VSRVQBQPZUROKPHPQWRF","WWSEGAQXYAYVUPQKSHZT","BTINIREZOYGMUATCAJZA","LZWFRMPJVRFZKNOSGTTU","RBHNCAPELQFWPDBGRQSN","HXOTMCOSVHPOLWBNYQRL","IYHYBKGTCYIMXWFLATEY","DTMORQDRIUCRVJPWVXRX","WZJVXPHAKNYNIMBZCESL","BUEWFTUAQMXONHMLYTLI"};
			int expected__            = 1043070;

			clock_t start__           = clock();
			int received__            = DistinguishableSetDiv1().count( vector <string>( answer, answer + ( sizeof answer / sizeof answer[0] ) ) );
			return verify_case( casenum, expected__, received__, clock()-start__ );
		}

		// custom cases

/*      case 5: {
			string answer[]           = ;
			int expected__            = ;

			clock_t start__           = clock();
			int received__            = DistinguishableSetDiv1().count( vector <string>( answer, answer + ( sizeof answer / sizeof answer[0] ) ) );
			return verify_case( casenum, expected__, received__, clock()-start__ );
		}*/
/*      case 6: {
			string answer[]           = ;
			int expected__            = ;

			clock_t start__           = clock();
			int received__            = DistinguishableSetDiv1().count( vector <string>( answer, answer + ( sizeof answer / sizeof answer[0] ) ) );
			return verify_case( casenum, expected__, received__, clock()-start__ );
		}*/
/*      case 7: {
			string answer[]           = ;
			int expected__            = ;

			clock_t start__           = clock();
			int received__            = DistinguishableSetDiv1().count( vector <string>( answer, answer + ( sizeof answer / sizeof answer[0] ) ) );
			return verify_case( casenum, expected__, received__, clock()-start__ );
		}*/
		default:
			return -1;
		}
	}
}
 

int main(int argc, char *argv[]) {
	if (argc == 1) {
		moj_harness::run_test();
	} else {
		for (int i=1; i<argc; ++i)
			moj_harness::run_test(atoi(argv[i]));
	}
}
// END CUT HERE
